name: "🤔 Solicitar novas funcionalidades"
description: Sugira ideias ou funcionalidades que você gostaria de ver implementadas no OpenManus.
labels: enhancement
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Descrição da funcionalidade
      description: |
        Forneça uma descrição clara e concisa da funcionalidade proposta
    validations:
      required: true
  - type: textarea
    id: your-feature
    attributes:
      label: Sua Funcionalidade
      description: |
        Explique sua ideia ou processo de implementação, se houver. Opcionalmente, inclua uma URL de Pull Request.
        Certifique-se de que a documentação/testes/exemplos correspondentes sejam fornecidos para revisão.
    validations:
      required: false
