name: "🪲 Mostre-me o Bug"
description: Relate um bug encontrado ao usar o OpenManus e procure assistência.
labels: bug
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Descrição do Bug
      description: |
        Descreva claramente o bug que você encontrou
    validations:
      required: true
  - type: textarea
    id: solve-method
    attributes:
      label: Método de resolução do Bug
      description: |
        Se resolvido, explique a solução. Opcionalmente, inclua uma URL de Pull Request.
        Se não resolvido, forneça detalhes adicionais para ajudar na investigação
    validations:
      required: true
  - type: textarea
    id: environment-information
    attributes:
      label: Informações do Ambiente
      description: |
        Sistema: ex., Ubuntu 22.04
        Python: ex., 3.12
        Versão do OpenManus: ex., 0.1.0
      value: |
        - Versão do Sistema:
        - Versão do Python:
        - Versão ou branch do OpenManus:
        - Método de instalação (ex., `pip install -r requirements.txt` ou `pip install -e .`):
    validations:
      required: true
  - type: textarea
    id: extra-information
    attributes:
      label: Informações Extras
      description: |
        Por exemplo, anexe capturas de tela ou logs para ajudar a diagnosticar o problema
    validations:
      required: false
