# Global LLM configuration
[llm]
model = "gpt-4o-mini"
base_url = "https://api.openai.com/v1"
api_key = "your openai api key"
max_tokens = 4096
temperature = 0.0

# Optional configuration for specific LLM models
[llm.vision]
model = "gpt-4o-mini"
base_url = "https://api.openai.com/v1"
api_key = "your openai api key"

# HoneyHive configuration
[honeyhive]
api_key = "your honeyhive api key"
project = "openmanus-trace"
source = "development"
session_name = "OpenManus Session"
