[contest]
theme = "春之韵"
max_words = 100
num_poets = 6

[scoring]
min_score = 0
max_score = 100
dimensions = ["theme_relevance", "language_beauty", "structure_completeness"]
weights = { "theme_relevance" = 0.4, "language_beauty" = 0.3, "structure_completeness" = 0.3 }

[output]
save_poems = true
save_scores = true
save_rankings = true
output_dir = "results" 